[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[build]
python_version = "3.10"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
